package com.chuidiang.rtsp;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fjabellan' at '2/05/18 11:11' with Gradle 3.1
 *
 * @author fjabellan, @date 2/05/18 11:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
