/*
 * Open API chuidiang example
 * El ejemplo maravilloso
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Data;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebService2Api
 */
@Ignore
public class WebService2ApiTest {

    private final WebService2Api api = new WebService2Api();

    
    /**
     * 
     *
     * Si me das una data, te lo devuelvo incrementado
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void greeting2Test() throws ApiException {
        Data data = null;
                Data response = api.greeting2(data);
        // TODO: test validations
    }
    
}
