/*
 * Open API chuidiang example
 * El ejemplo maravilloso
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * un data
 */
@ApiModel(description = "un data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-23T21:24:11.453724300+02:00[Europe/Paris]")
public class Data {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private Integer value;

  public static final String SERIALIZED_NAME_STRING = "string";
  @SerializedName(SERIALIZED_NAME_STRING)
  private String string;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private OffsetDateTime date;

  public Data() { 
  }

  public Data value(Integer value) {
    
    this.value = value;
    return this;
  }

   /**
   * Entre 0 y 10
   * minimum: 0
   * maximum: 10
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Entre 0 y 10")

  public Integer getValue() {
    return value;
  }


  public void setValue(Integer value) {
    this.value = value;
  }


  public Data string(String string) {
    
    this.string = string;
    return this;
  }

   /**
   * maximo 20
   * @return string
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "maximo 20")

  public String getString() {
    return string;
  }


  public void setString(String string) {
    this.string = string;
  }


  public Data date(OffsetDateTime date) {
    
    this.date = date;
    return this;
  }

   /**
   * un dia guay
   * @return date
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "un dia guay")

  public OffsetDateTime getDate() {
    return date;
  }


  public void setDate(OffsetDateTime date) {
    this.date = date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data data = (Data) o;
    return Objects.equals(this.value, data.value) &&
        Objects.equals(this.string, data.string) &&
        Objects.equals(this.date, data.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, string, date);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    string: ").append(toIndentedString(string)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

