import com.chuidiang.rtsp.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'fjabellan' at '2/05/18 11:11' with Gradle 3.1
 *
 * @author fjabellan, @date 2/05/18 11:11
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
